FROM ruby

LABEL maintainer="Eero Virta <eero.virta@patreon.me>"

RUN apt update && apt install -y python3-pip cron \
        && pip install json-spec \
        && pip install publicsuffix \
        && gem install whois \
        && gem install whois-parser

VOLUME /tmp
WORKDIR /tmp

COPY entrypoint.sh /entrypoint.sh
COPY crontab /etc/crontab
COPY domlist.py test.rb /opt/

ENTRYPOINT ["/entrypoint.sh"]
CMD [ "/usr/sbin/cron", "-f", "-L", "15"]

